### PR TITLE
Update cardano-mdp.json to add NEP

### PR DESCRIPTION
**Pull request by voyagerstakepool**

### CODE REVIEW

**Comment by ResponsibleStaking** [comment]
Donation strategy with 20% is OK.
Anyways there there is no proof of the donations avaible. So please announce them somewhere publically visible and regsiter them in the Donations Repo

**Comment by julienadatrain** [comment]
Hello @ResponsibleStaking 

Proof of donations to the 3 charities here on twitter:

https://twitter.com/PoolVoyager/status/1409839173746503680
https://twitter.com/PoolVoyager/status/1409837240361041920
https://twitter.com/PoolVoyager/status/1409840841745653763

**Comment by ResponsibleStaking** [comment]
Please register the doncations in the GitHub Repo. We need this to be able to count summaries. Thank you!

**Comment by BrianLee12** [comment]
Requests have been fulfilled, thank you!

**Pull request merged**
