### PR TITLE
COINZ Registration

### PR DESCRIPTION
**Pull request by cxhercules**

### CODE REVIEW

**Comment by BrianLee12** [comment]
Hey cxhercules , I see on your website that you have a ledger of donations but no donation receipts. Please post your donation receipts to your website so that we can continue with your pull request.
Also, please post your donation receipts to https://github.com/CardanoMDP/Donations so that we can keep a running total for the group. Thank you!

**Comment by cxhercules** [comment]
I have posted a pdf much like what you showed me here, https://adacoinz.com/assets/donations/donations.pdf. I have updated links according in my site. 

I will look at other requirement shortly.

**Comment by BrianLee12** [comment]
Thanks for making the changes cxhercules, I've merged this in another request since GitHub wouldn't let me easily do it through yours :)

**Comment by cxhercules** [comment]
Thank you, I have been busy :( as are we all! Maybe over extended a bit.

**Pull request closed without merging**
