### PR TITLE
Add [ENVIR] to pool list, Update ALPS

### PR DESCRIPTION
**Pull request by lukas-kamleitner**

### CODE REVIEW

**Comment by kiriakos** [comment]
Hey there! :wave: 

As discussed in the Cardano MDP telegram chat we will be adding official inclusion guidelines at the end of the month and are currently working on designing them. Untill the pollicies have been established (probably early March)  we will not be processing merge requests.

Regards,
k

**Comment by kiriakos** [comment]
Hi there, can you update the PR with the current cardano-mdp.json?

**Comment by kiriakos** [comment]
ping @lukas-kamleitner

**Comment by lukas-kamleitner** [comment]
Updated the description of my pool ALPS (already part of MDP)
Added my second pool ENVIR to the list

**Comment by kiriakos** [comment]
Hi there,

according to the MDP membership requirements, minting pools need to at least donate 10% of pool profit for operators of pool groups this is currently based on all profits from all their pools. I'm not sure your donation commitment of 500€ per year would satisfy that requirement. Are you open to adjust that?

Link: https://discord.com/channels/821088538538803230/821142135650779237/823758612928659496

**Comment by lukas-kamleitner** [comment]
Hi,

if 1000€ / year of donations is not enough to be part of the group, then please just remove my existing pool ALPS from the group and do not add ENVIR.

KR

**Pull request closed without merging**
