### PR TITLE
Update cardano-mdp.json

### PR DESCRIPTION
**Pull request by Faabster91**
Adding Mokum Stake Pool

### CODE REVIEW

**Comment by BrianLee12** [comment]
Hey Fabian, thanks for your pull request! I had a look at your website, and there are some things that are missing that you'll need to update before I can merge your pull request:

- You'll need to post your % of pool income or profits that you plan on donating to your chosen mission (MDP minimum is 10% of pool profits)

- You'll need a chosen donation schedule (monthly, quarterly, etc.) also posted to your website. Since you aren't making a profit yet, donations aren't required yet, but you'll still need to show what that schedule will be when you do start making a profit.

- You'll need a clear spot for donations to be posted when you do start making a profit & donations. For now you can mention in that spot that once your pool is making a profit you'll be making consistent donations. You can also link to your MDP GitHub donations page when you start donating so that you don't have to post donations twice if it is easier :)

It would also be a good idea to have a link to the Save the Children website from your website (more credibility for you) :)

Thanks very much for making the changes, and looking forward to adding your pool to the MDP list soon!

Brian

**Comment by Faabster91** [comment]
Hello Brian,

I have provided all the detailed information about my donations and the
calculation of my donations on the donations
<https://mokumstakepool.com/donations/> page on my website, including % of
pool profits, schedule of donations and proof of donations.
Thanks for your suggestion about linking to the website of Save the
Children, I will continue to work on updating the site.
Hope this answers all your questions and please let me know if anything
else is needed.

Best regards,
Fabian

**Comment by BrianLee12** [comment]
Hey Fabian, thanks for getting those changes made so quickly! The only thing I see as a potential issue is the calculation of profit: "The pool’s profit, also called the margin fee, is donated".

For MDP, profit is calculated as a business would calculate profit: income - expenses  = profit.
Income = Margin + Minimum Cost Per Epoch.

So at a bare minimum, you'll need a note saying 10% of pool profits for donations for MDP compliance.

Once you've got this adjusted, I can approve your pull request. Also, nice work on making your first donation regardless of making a profit!!! 

All the best,

Brian

**Comment by Faabster91** [comment]
Hi Brian,

I decided to commit to donate at least 10% of total pool income (not pool's
profit) and I have added this on my site.
I realize this is more than required for MDP, but to me this is more
transparent as compared to using a percentage of profit (as usual
businesses would calculate it) since there is no way to verify pool
expenses for the outside.

Best,
Fabian

**Comment by BrianLee12** [comment]
Awesome, that's great Fabian! Thanks so much for doing this, and yes it is easier to prove donations if it is from income instead of profit :)
Nice work!

**Comment by Faabster91** [comment]
Hi Brian,

Thanks a lot!
I have also updated the Google doc with my pool info for the website.
I don't have a custom logo yet, but I added the Cardano logo here which you
can use meanwhile.

Best,
Fabian

[image: cardano-ada-logo.png]

**Pull request merged**
